- name: Wait cloud-init
  ansible.builtin.command:
    cloud-init status
  register: cloudinit_status
  retries: 5
  delay: 10
  until: "'done' in cloudinit_status.stdout"
  changed_when: false
  failed_when: false

- name: Reset kubeadm
  ansible.builtin.include_tasks:
    file: reset-kubeadm.yml

- name: Disable haproxy / keepalived / kubelet / containerd
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - haproxy
    - keepalived
    - kubelet
    - containerd
  failed_when: false

- name: Reboot
  ansible.builtin.reboot:
    reboot_timeout: 300
    connect_timeout: 300
