- name: Dynamically create the proxmox_vms list
  ansible.builtin.set_fact:
    proxmox_vms: |
      {% set temp_list = [] %}
      {% for item in proxmox_vms_template %}
      {%   set _ = temp_list.append({
              "vmid": (subnet_third_octet * 1000) + (10 + item.seq_no),
              "name": "pve-192-168-" ~ subnet_third_octet ~ "-" ~ (10 + item.seq_no),
              "node": item.node,
              "mac": "0a:00:00:00:" ~ ('%02x' | format(subnet_third_octet)) ~ ":" ~ ('%02x' | format(10 + item.seq_no)),
              "ip": "192.168." ~ subnet_third_octet ~ "." ~ (10 + item.seq_no),
              "user": proxmox_vm_default_user,
              "password": proxmox_vm_default_password,
            })
      %}
      {% endfor %}
      {{ temp_list }}

- name: Debug proxmox_vms
  ansible.builtin.debug:
    var: proxmox_vms

- name: Dynamically create the router_vm
  ansible.builtin.set_fact:
    router_vm:
      vmid: "{{ (subnet_third_octet * 1000) + 1 }}"
      name: "pve-192-168-{{ subnet_third_octet }}-1---{{ router_vm_template.wan_ip | replace('.', '-') }}"
      node: "{{ router_vm_template.node }}"
      ip: "{{ router_vm_template.wan_ip }}"

- name: Debug router_vm
  ansible.builtin.debug:
    var: router_vm
