all: # noqa: syntax-check[specific]
  vars:
    ansible_ssh_private_key_file: ./.ssh/id_rsa
  hosts:
    oc1-nuc-1:
      ansible_host: 192.168.5.21
      ansible_user: $OC1_NUC_1_USER
    oc1-nuc-2:
      ansible_host: 192.168.5.22
      ansible_user: $OC1_NUC_2_USER
