all: # noqa: syntax-check[specific]
  vars:
    ansible_ssh_private_key_file: ./.ssh/id_rsa
  hosts:
    oc1-nuc-1:
      ansible_host: 192.168.5.21
      ansible_user: root
    oc1-nuc-2:
      ansible_host: 192.168.5.22
      ansible_user: root
    oc1-server1:
      ansible_host: 192.168.5.25
      ansible_user: root
    # oc1-server2:
    #   ansible_host: 192.168.5.26
    #   ansible_user: root
