- name: Setup VM
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts: oc1-server1
  become: true
  vars:
    vm:
      - target_host: oc1-server1
        vmid: 5161
        options: "--memory 2048 --cores 1 --name oc1-dns \
          --net0 virtio,bridge=vmbr0 --ipconfig0 ip=192.168.5.161/24,gw=192.168.5.1"
        healthcheck_ip: 192.168.5.161
  roles:
    - destroy-vm
    - create-vm
    - start-vm
