- name: Setup VM
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts: oc1-nuc-1
  become: true
  vars:
    vm:
      - target_host: oc1-nuc-1
        vmid: 100
        options: "--memory 4096 --cores 2 --name oc1-nfs --ipconfig0 ip=192.168.5.151/24,gw=192.168.5.1"
        healthcheck_ip: 192.168.5.151
        device_id: 0bda:9210
  roles:
    - destroy-vm
    - create-vm
    - attach-hardware
    - start-vm
