- name: Setup VM
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts: all
  become: true
  vars:
    vm:
      - target_host: oc1-nuc-1
        vmid: 3001
        options: "--memory 4096 --cores 2 --name oc1-vm-1 --ipconfig0 ip=192.168.5.31/24,gw=192.168.5.1"
        healthcheck_ip: 192.168.5.31
      - target_host: oc1-nuc-2
        vmid: 3002
        options: "--memory 32768 --cores 2 --name oc1-vm-2 --ipconfig0 ip=192.168.5.32/24,gw=192.168.5.1"
        healthcheck_ip: 192.168.5.32
      - target_host: oc1-nuc-1
        vmid: 9001
        options: "--memory 4096 --cores 2 --name oc1-lb-1 --ipconfig0 ip=192.168.5.91/24,gw=192.168.5.1"
        healthcheck_ip: 192.168.5.91
      - target_host: oc1-nuc-2
        vmid: 9002
        options: "--memory 32768 --cores 2 --name oc1-lb-2 --ipconfig0 ip=192.168.5.92/24,gw=192.168.5.1"
        healthcheck_ip: 192.168.5.92
  roles:
    - destroy-vm
    - create-vm
