- name: Setup VM
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts: oc1-server1
  become: true
  vars:
    vm:
      - target_host: oc1-server1
        vmid: 5160
        options: "--memory 4096 --cores 2 --name oc1-proxy \
          --net0 virtio,bridge=vmbr0 --ipconfig0 ip=192.168.5.160/24,gw=192.168.5.1 \
          --net1 virtio,bridge=vmbr1 --ipconfig1 ip=192.168.1.70/24"
        healthcheck_ip: 192.168.5.160
  roles:
    - destroy-vm
    - create-vm
    - start-vm
