- name: Setup VM
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts: oc1-server1
  become: true
  vars:
    vm:
      - target_host: oc1-server1
        vmid: 5152
        options: "--memory 4096 --cores 2 --name oc1-backup-smb \
          --ipconfig0 ip=192.168.5.152/24,gw=192.168.5.1"
        healthcheck_ip: 192.168.5.152
  roles:
    # - destroy-vm 誤って削除しないようコメントアウト
    - create-vm
    - start-vm
