#!/bin/bash

# スクリプトの絶対パスを取得
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ==========================================
# 設定: "ホスト名:IPアドレス" の形式で記述
# ==========================================
NODES=(
    "dev-server:192.168.5.199"
)

# 共通設定（SCRIPT_DIRをベースにする）
USER_NAME="ubuntu"
KEY_DIR="$SCRIPT_DIR/keys"
CONF_FILE="$SCRIPT_DIR/ssh_config"

# ディレクトリ準備
mkdir -p "$KEY_DIR"

# 初期化
echo "# Generated by gen-keys.sh - $(date)" > "$CONF_FILE"

for entry in "${NODES[@]}"; do
    host="${entry%%:*}"
    ip="${entry#*:}"

    PRIVATE_KEY="$KEY_DIR/$host"

    # 1. 鍵の生成
    if [ ! -f "$PRIVATE_KEY" ]; then
        ssh-keygen -t ed25519 -f "$PRIVATE_KEY" -N "" -q
    fi

    # 2. SSH Config への書き出し
    # IdentityFile を $SCRIPT_DIR ベースに変更
    cat <<EOF >> "$CONF_FILE"
Host $host
    HostName $ip
    User $USER_NAME
    IdentityFile $KEY_DIR/$host
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    LogLevel ERROR

EOF

done

echo "✅ SSH config updated: $CONF_FILE"
