- name: Set subnets_config
  ansible.builtin.set_fact:
    subnets_config: |
      {% set result = [] %}
      {% for subnet in input.subnets %}
      {%   set ip_parts = subnet.cidr.split('/') | first | split('.') %}
      {%   set first_octet = ip_parts[0] %}
      {%   set second_octet = ip_parts[1] %}
      {%   set third_octet = ip_parts[2] %}
      {%   set netmask = subnet.cidr.split('/')[1] %}
      {%   set gateway_ip = first_octet ~ '.' ~ second_octet ~ '.' ~ third_octet ~ '.1' %}
      {%   set pve_nodes = [] %}
      {%   for i in range(1, 4) %}
      {%     set ip = first_octet ~ '.' ~ second_octet ~ '.' ~ third_octet ~ '.' ~ (10 + i) %}
      {%     set _ = pve_nodes.append({
               "vmid": (subnet.vlan_id * 100) + (10 + i),
               "name": subnet.name ~ '---' ~ (ip | replace('.', '-')),
               "node": subnet.node,
               "mac":
                 "0a:00"
                 ~ ":" ~ ('%02x' | format(first_octet | int))
                 ~ ":" ~ ('%02x' | format(second_octet | int))
                 ~ ":" ~ ('%02x' | format(third_octet | int))
                 ~ ":" ~ ('%02x' | format(10 + i)),
                "ip": ip,
                "user": proxmox_vm_default_user,
                "password": proxmox_vm_default_password,
                "vlan_id": subnet.vlan_id,
             })
      %}
      {%   endfor %}
      {%   set _ = result.append({
              "name": subnet.name,
              "node": subnet.node,
              "cidr": subnet.cidr,
              "vlan_id": subnet.vlan_id,
              "bridge": bridge_name,
              "first_octet": first_octet | int,
              "second_octet": second_octet | int,
              "third_octet": third_octet | int,
              "start_ip": first_octet ~ '.' ~ second_octet ~ '.' ~ third_octet ~ '.10',
              "end_ip": first_octet ~ '.' ~ second_octet ~ '.' ~ third_octet ~ '.250',
              "netmask": netmask,
              "public_ip": subnet.public_ip,
              "gateway": {
                "vmid": (subnet.vlan_id * 100) + 1,
                "name": subnet.name ~ '---' ~ (gateway_ip | replace('.', '-')),
                "node": subnet.node,
                "ip": gateway_ip,
                "netmask": netmask,
                "subnet_third_octet": third_octet,
                "vlan_id": subnet.vlan_id,
                "public_ip": subnet.public_ip,
              },
              "pve_nodes": pve_nodes,
            })
      %}
      {% endfor %}
      {{ result }}

- name: Set pve_nodes
  ansible.builtin.set_fact:
    pve_nodes: "{{ subnets_config | map(attribute='pve_nodes') | list | flatten }}"

- name: Debug config
  ansible.builtin.debug:
    msg: "{{ subnets_config }}"
