// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/ai_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Instructions  string                 `protobuf:"bytes,2,opt,name=instructions,proto3" json:"instructions,omitempty"` // レポート生成のための指示内容
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                 // レポート生成に使用するデータ
	Context       string                 `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`           // データ収集に必要なコンテキスト（例: 期間、対象リソースなど）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportRequest) Reset() {
	*x = GenerateReportRequest{}
	mi := &file_proto_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportRequest) ProtoMessage() {}

func (x *GenerateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportRequest.ProtoReflect.Descriptor instead.
func (*GenerateReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateReportRequest) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *GenerateReportRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GenerateReportRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type GenerateReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         string                 `protobuf:"bytes,1,opt,name=tasks,proto3" json:"tasks,omitempty"`
	Thinking      string                 `protobuf:"bytes,2,opt,name=thinking,proto3" json:"thinking,omitempty"`
	Report        *Report                `protobuf:"bytes,3,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportResponse) Reset() {
	*x = GenerateReportResponse{}
	mi := &file_proto_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportResponse) ProtoMessage() {}

func (x *GenerateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportResponse.ProtoReflect.Descriptor instead.
func (*GenerateReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateReportResponse) GetTasks() string {
	if x != nil {
		return x.Tasks
	}
	return ""
}

func (x *GenerateReportResponse) GetThinking() string {
	if x != nil {
		return x.Thinking
	}
	return ""
}

func (x *GenerateReportResponse) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

type Report struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_proto_ai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{2}
}

func (x *Report) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Report) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_proto_ai_service_proto protoreflect.FileDescriptor

const file_proto_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x16proto/ai_service.proto\x12\n" +
	"ai_service\"\x82\x01\n" +
	"\x15GenerateReportRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\"\n" +
	"\finstructions\x18\x02 \x01(\tR\finstructions\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x18\n" +
	"\acontext\x18\x04 \x01(\tR\acontext\"v\n" +
	"\x16GenerateReportResponse\x12\x14\n" +
	"\x05tasks\x18\x01 \x01(\tR\x05tasks\x12\x1a\n" +
	"\bthinking\x18\x02 \x01(\tR\bthinking\x12*\n" +
	"\x06report\x18\x03 \x01(\v2\x12.ai_service.ReportR\x06report\"2\n" +
	"\x06Report\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body2f\n" +
	"\tAIService\x12Y\n" +
	"\x0eGenerateReport\x12!.ai_service.GenerateReportRequest\x1a\".ai_service.GenerateReportResponse0\x01B<Z:github.com/nuage-cluster/monitoring-stack/ai-service/protob\x06proto3"

var (
	file_proto_ai_service_proto_rawDescOnce sync.Once
	file_proto_ai_service_proto_rawDescData []byte
)

func file_proto_ai_service_proto_rawDescGZIP() []byte {
	file_proto_ai_service_proto_rawDescOnce.Do(func() {
		file_proto_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_service_proto_rawDesc), len(file_proto_ai_service_proto_rawDesc)))
	})
	return file_proto_ai_service_proto_rawDescData
}

var file_proto_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_ai_service_proto_goTypes = []any{
	(*GenerateReportRequest)(nil),  // 0: ai_service.GenerateReportRequest
	(*GenerateReportResponse)(nil), // 1: ai_service.GenerateReportResponse
	(*Report)(nil),                 // 2: ai_service.Report
}
var file_proto_ai_service_proto_depIdxs = []int32{
	2, // 0: ai_service.GenerateReportResponse.report:type_name -> ai_service.Report
	0, // 1: ai_service.AIService.GenerateReport:input_type -> ai_service.GenerateReportRequest
	1, // 2: ai_service.AIService.GenerateReport:output_type -> ai_service.GenerateReportResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ai_service_proto_init() }
func file_proto_ai_service_proto_init() {
	if File_proto_ai_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_service_proto_rawDesc), len(file_proto_ai_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_service_proto_goTypes,
		DependencyIndexes: file_proto_ai_service_proto_depIdxs,
		MessageInfos:      file_proto_ai_service_proto_msgTypes,
	}.Build()
	File_proto_ai_service_proto = out.File
	file_proto_ai_service_proto_goTypes = nil
	file_proto_ai_service_proto_depIdxs = nil
}
