all: # noqa: syntax-check[specific]
  vars:
    ansible_ssh_private_key_file: ./.ssh/id_rsa
  hosts:
    load-balancer-01:
      ansible_host: 192.168.5.51
      ansible_user: ubuntu
    load-balancer-02:
      ansible_host: 192.168.5.52
      ansible_user: ubuntu

    control-plane-01:
      ansible_host: 192.168.5.61
      ansible_user: ubuntu
    control-plane-02:
      ansible_host: 192.168.5.62
      ansible_user: ubuntu
    control-plane-03:
      ansible_host: 192.168.5.63
      ansible_user: ubuntu

    worker-node-01:
      ansible_host: 192.168.5.71
      ansible_user: ubuntu
    worker-node-02:
      ansible_host: 192.168.5.72
      ansible_user: ubuntu
    worker-node-device-host-01:
      ansible_host: 192.168.5.83
      ansible_user: ubuntu
    # oc1-pi-2:
    #   ansible_host: 192.168.5.12
    #   ansible_user: nuage
  children:
    loadbalancer:
      hosts:
        load-balancer-01:
        load-balancer-02:
    control-plane:
      hosts:
        control-plane-01:
        control-plane-02:
        control-plane-03:
    worker-node:
      hosts:
        worker-node-01:
        worker-node-02:
        worker-node-device-host-01:
        # oc1-pi-2:
