all: # noqa: syntax-check[specific]
  vars:
    ansible_ssh_private_key_file: ./.ssh/id_rsa
  hosts:
    oc1-pi-1:
      ansible_host: 192.168.5.11
      ansible_user: $OC1_PI_1_USER
    oc1-pi-2:
      ansible_host: 192.168.5.12
      ansible_user: $OC1_PI_2_USER
    oc1-pi-3:
      ansible_host: 192.168.5.13
      ansible_user: $OC1_PI_3_USER
    oc1-pi-4:
      ansible_host: 192.168.5.14
      ansible_user: $OC1_PI_4_USER
    oc1-vm-1:
      ansible_host: 192.168.5.31
      ansible_user: $OC1_VM_1_USER
    oc1-vm-2:
      ansible_host: 192.168.5.32
      ansible_user: $OC1_VM_2_USER
    oc2-pi-1:
      ansible_host: 192.168.6.11
      ansible_user: $OC2_PI_1_USER
    oc2-pi-2:
      ansible_host: 192.168.6.12
      ansible_user: $OC2_PI_2_USER
    oc2-pi-3:
      ansible_host: 192.168.6.13
      ansible_user: nuage
    oc1-lb-1:
      ansible_host: 192.168.5.91
      ansible_user: ubuntu
    oc1-lb-2:
      ansible_host: 192.168.5.92
      ansible_user: ubuntu
  children:
    control-plane:
      hosts:
        oc1-pi-1:
        oc1-vm-1:
        oc2-pi-1:
    node:
      hosts:
        oc1-pi-2:
        oc1-pi-3:
        oc1-pi-4:
        oc1-vm-2:
        oc2-pi-2:
        oc2-pi-3:
    lb:
      hosts:
        oc1-lb-1:
        oc1-lb-2:
