all: # noqa: syntax-check[specific]
  vars:
    ansible_ssh_private_key_file: ./.ssh/id_rsa
  hosts:
    oc1-pi-1:
      ansible_host: 192.168.5.11
      ansible_user: nuage
    oc1-pi-2:
      ansible_host: 192.168.5.12
      ansible_user: nuage
    # oc1-pi-3:
    #   ansible_host: 192.168.5.13
    #   ansible_user: nuage
    # oc1-pi-4:
    #   ansible_host: 192.168.5.14
    #   ansible_user: nuage
    oc1-vm-1:
      ansible_host: 192.168.5.31
      ansible_user: ubuntu
    oc1-vm-2:
      ansible_host: 192.168.5.32
      ansible_user: ubuntu
    oc1-vm-3:
      ansible_host: 192.168.5.33
      ansible_user: ubuntu
    oc1-vm-4:
      ansible_host: 192.168.5.34
      ansible_user: ubuntu
    oc2-pi-1:
      ansible_host: 192.168.6.11
      ansible_user: nuage
    oc2-pi-2:
      ansible_host: 192.168.6.12
      ansible_user: nuage
    oc2-pi-3:
      ansible_host: 192.168.6.13
      ansible_user: nuage
  children:
    loadbalancer:
      hosts:
        oc1-vm-1:
        oc1-pi-1:
        oc2-pi-1:
    control-plane:
      hosts:
        oc1-vm-2:
        oc1-pi-2:
        oc2-pi-2:
    worker-node:
      hosts:
        oc1-vm-3:
        oc1-vm-4:
        oc2-pi-3:
