- name: Setup hosts
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts: all
  become: true
  roles:
    - setup-hosts

- name: Setup LB
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts:
    - load-balancer
  become: true
  roles:
    - setup-lb

- name: Setup cluster
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts:
    - control-plane
    - node
  become: true
  roles:
    - setup-kubeadm
    - setup-cluster
