- name: Reset hosts
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts: all
  become: true
  roles:
    - reset-hosts

- name: Setup loadbalancer
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts:
    - loadbalancer
  become: true
  roles:
    - setup-loadbalancer

- name: Setup kubeadm
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts:
    - control-plane
    - worker-node
  become: true
  roles:
    - setup-kubeadm

- name: Init control plane
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts:
    - control-plane[0]
  become: true
  roles:
    - init-control-plane

- name: Get Join Command
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts:
    - control-plane[0]
  become: true
  roles:
    - get-join-command

- name: Join control plane
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts:
    - control-plane
  become: true
  roles:
    - role: join-control-plane
      when: inventory_hostname in groups['control-plane'][1:]

- name: Join worker node
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts:
    - worker-node
  become: true
  roles:
    - join-worker-node

- name: Wait cluster ready
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts:
    - control-plane[0]
  become: true
  roles:
    - wait-cluster-ready
