- name: Setup hosts
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts: all
  become: true
  roles:
    - setup-hosts

- name: Setup Cluster LB
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts:
    - cluster-lb
  become: true
  roles:
    - setup-cluster-lb

- name: Setup cluster
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts:
    - control-plane
    - node
  become: true
  roles:
    - setup-kubeadm
    - setup-cluster

- name: Setup Service LB
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts:
    - service-lb
  become: true
  roles:
    - setup-service-lb
