apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy
spec:
  selector:
    matchLabels:
      app: ntfy
  template:
    metadata:
      labels:
        app: ntfy
    spec:
      containers:
      - name: ntfy
        image: binwiederhier/ntfy
        args: ["serve"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: config
          mountPath: "/etc/ntfy"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: ntfy
---
# Basic service for port 80
apiVersion: v1
kind: Service
metadata:
  name: ntfy
  namespace: nuage-monitoring
spec:
  selector:
    app: ntfy
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy
  namespace: nuage-monitoring
data:
  server.yml: |
    # Template: https://github.com/binwiederhier/ntfy/blob/main/server/server.yml
    base-url: https://ntfy.sh
    web-push-public-key: BDfug3S5RCDl4deQPq1kgMBj4xBe0SUmt1kHSjn8cmhG8L2E6qguHUx97OMH7ffNy9eCBJ59eAG5gvzwIKUFENM
    web-push-private-key: KDcbY7Kvh0-tn9sljndIMtPQZOBUSOM3wE4LgJeeH_g
    web-push-file: /var/webpush.db # or similar
    web-push-email-address: email
