- name: Get Proxmox API authentication ticket
  ansible.builtin.uri:
    url: "https://{{ pve_nodes[0].api_host }}:8006/api2/json/access/ticket"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ pve_nodes[0].api_user }}"
      password: "{{ pve_nodes[0].api_password }}"
    validate_certs: false
    status_code: 200
  register: auth_ticket

- name: Wait until quorum is established
  ansible.builtin.uri:
    url: "https://{{ pve_nodes[0].api_host }}:8006/api2/json/cluster/status"
    method: GET
    headers:
      Cookie: "PVEAuthCookie={{ auth_ticket.json.data.ticket }}"
    validate_certs: false
    status_code: 200
  register: cluster_status
  until: >
    cluster_status.status == 200 and
    'json' in cluster_status and
    (cluster_info | length) > 0 and
    cluster_info[0].quorate == 1
  vars:
    cluster_info: "{{ cluster_status.json.data | selectattr('id', 'equalto', 'cluster') | list }}"
  retries: 10
  delay: 10

- name: Join a Proxmox VE Cluster
  community.proxmox.proxmox_cluster:
    state: present
    api_host: "{{ item.api_host }}"
    api_user: "{{ item.api_user }}"
    api_password: "{{ item.api_password }}"
    master_ip: "{{ proxmox_cluster_join.cluster_join.nodelist[0].pve_addr }}"
    fingerprint: "{{ proxmox_cluster_join.cluster_join.nodelist[0].pve_fp }}"
    cluster_name: "{{ proxmox_cluster_join.cluster_join.totem.cluster_name }}"
