# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: report_service.proto for package 'gateway'

require 'grpc'
require 'report_service_pb'

module Gateway
  module ReportService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gateway.ReportService'

      rpc :GetReport, ::Gateway::GetReportRequest, ::Gateway::GetReportResponse
      rpc :ListReports, ::Gateway::ListReportsRequest, ::Gateway::ListReportsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
