# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: report_service.proto

require 'google/protobuf'


descriptor_data = "\n\x14report_service.proto\x12\x07gateway\"|\n\x06Report\x12\x11\n\treport_id\x18\x01 \x01(\t\x12\x13\n\x0breport_name\x18\x02 \x01(\t\x12\x13\n\x0breport_type\x18\x03 \x01(\t\x12\x14\n\x0cgenerated_at\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\"%\n\x10GetReportRequest\x12\x11\n\treport_id\x18\x01 \x01(\t\"4\n\x11GetReportResponse\x12\x1f\n\x06report\x18\x01 \x01(\x0b\x32\x0f.gateway.Report\"n\n\x12ListReportsRequest\x12\x13\n\x0breport_type\x18\x01 \x01(\t\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\x12\r\n\x05limit\x18\x04 \x01(\x05\x12\x0e\n\x06offset\x18\x05 \x01(\x05\"7\n\x13ListReportsResponse\x12 \n\x07reports\x18\x01 \x03(\x0b\x32\x0f.gateway.Report2\x9d\x01\n\rReportService\x12\x42\n\tGetReport\x12\x19.gateway.GetReportRequest\x1a\x1a.gateway.GetReportResponse\x12H\n\x0bListReports\x12\x1b.gateway.ListReportsRequest\x1a\x1c.gateway.ListReportsResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Gateway
  Report = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.Report").msgclass
  GetReportRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.GetReportRequest").msgclass
  GetReportResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.GetReportResponse").msgclass
  ListReportsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.ListReportsRequest").msgclass
  ListReportsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.ListReportsResponse").msgclass
end
