keys:
  - &admin_key     age17e67u5g3j9v6sxxrk448gsgmv9ldc2umqgad579du75fgjkjtcasatrhxr
  - &lb_key        age1g72ttt26gqzjt39nj423vkqtrt7t02x0qdz9g8yvc27eru0cuu4qte2u04

creation_rules:
  - path_regex: terraform/secrets\.yaml$
    key_groups:
      - age:
          - *admin_key
  - path_regex: truenas/secrets\.yaml$
    key_groups:
      - age:
          - *admin_key

  - path_regex: nix/hosts/loadbalancer/secrets\.yaml$
    key_groups:
      - age:
          - *admin_key
          - *lb_key
