- name: Install common packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - apt-transport-https
      - gpg
      - nfs-common
    state: present
    update_cache: true

- name: Create apt keyrings directory for Docker
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Apt arch
  ansible.builtin.command:
    dpkg --print-architecture
  register: apt_arch
  changed_when: false

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ apt_arch.stdout }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: true

- name: Install containerd.io
  ansible.builtin.apt:
    name: containerd.io
    state: present

- name: Add Kubernetes GPG key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    state: present

- name: Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    state: present
    filename: kubernetes
    update_cache: true

- name: Update apt cache after adding all repositories
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600 # Update if older than 1 hour

- name: Install Kubernetes packages
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
  notify:
    - Restart kubelet
    - Restart containerd

- name: Hold Kubernetes Packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubelet
    - kubeadm
    - kubectl
