- name: Wait for cloud-init to finish
  ansible.builtin.command:
    cmd: "cloud-init status --wait"
  register: cloudinit_status
  failed_when: cloudinit_status.rc not in [0, 2]
  changed_when: false
