apiVersion: v1
kind: Service
metadata:
  name: argo-server
  namespace: argo
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.5.101
  ports:
    - name: web
      port: 443
      targetPort: 2746
      protocol: TCP
      nodePort: 30000
  selector:
    app: argo-server
