apiVersion: v1
kind: Service
metadata:
  name: argo-server
  namespace: argo
spec:
  type: NodePort
  ports:
    - name: web
      port: 443
      targetPort: 2746
      protocol: TCP
      nodePort: 30002
  selector:
    app: argo-server
