- name: Attach hardware to VM
  ansible.builtin.shell: |
    qm set {{ item.vmid }} -usb0 host={{ item.device_id }},usb3=1
  register: result
  changed_when: result.rc == 0
  when: inventory_hostname == item.target_host and item.device_id is defined
  loop: "{{ vm }}"
