- name: Setup loadbalancer
  hosts:
    - k8s-loadbalancers
  become: true
  roles:
    - k8s-loadbalancer

- name: Setup control plane
  hosts:
    - k8s-control-planes[0]
  become: true
  roles:
    - k8s-reset
    - k8s-node
    - k8s-init-control-plane
    - k8s-get-join-info

- name: Join nodes
  hosts:
    - k8s-control-planes[1:]
    - k8s-worker-nodes
  become: true
  roles:
    - k8s-reset
    - k8s-node
    - k8s-join-node
