apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications-prod
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          # 外部リポジトリ（自動イメージ更新あり）
          - repository: bare-web-proxy
            repoURL: https://github.com/k-wa-wa/bare-web-proxy
            path: k8s/overlays/prod
            imageName: ghcr.io/k-wa-wa/bare-web-proxy
            imageTag: latest
            updateStrategy: digest
          # 自モノレポ（システムアプリ）
          - repository: cert-manager
            repoURL: https://github.com/k-wa-wa/nuage-cluster
            path: manifests/apps/cert-manager/overlays/prod
            # 条件分岐によるYAMLパースエラーを防ぐため、上書き不要なアプリにはダミーの値を指定する
            imageName: dummy
            imageTag: latest
            updateStrategy: digest
  template:
    metadata:
      name: '{{.repository}}-prod'
      annotations:
        # アノテーションを条件分岐なしで常に生成する
        argocd-image-updater.argoproj.io/image-list: 'myapp={{.imageName}}:{{.imageTag}}'
        argocd-image-updater.argoproj.io/myapp.update-strategy: '{{.updateStrategy}}'
    spec:
      project: default
      source:
        repoURL: '{{.repoURL}}'
        targetRevision: HEAD # Image Updaterが実体イメージを上書きするためHEAD固定でOK
        path: '{{.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.repository}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
