apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bare-web-proxy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/k-wa-wa/bare-web-proxy
    targetRevision: master
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: bare-web-proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bare-web-proxy-ingress
  namespace: bare-web-proxy
  annotations:
    cert-manager.io/cluster-issuer: "ca-clusterissuer"
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - bwproxy.cluster.wpc
    secretName: bare-web-proxy-tls-secret
  rules:
  - host: bwproxy.cluster.wpc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bare-web-proxy-service
            port:
              number: 80
