apiVersion: v1
kind: ConfigMap
metadata:
  name: varnish-config
  namespace: public
data:
  default.vcl: |
    vcl 4.1;

    backend default {
        .host = "192.168.5.151";
        .port = "9000";
    }

    sub vcl_deliver {
        # クライアントにコンテンツを返す直前の処理
        # キャッシュの状態を示すヘッダーを追加
        if (obj.hits > 0) {
            set resp.http.X-Cache = "HIT";
        } else {
            set resp.http.X-Cache = "MISS";
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish
  namespace: public
spec:
  selector:
    matchLabels:
      app: varnish
  template:
    metadata:
      labels:
        app: varnish
    spec:
      containers:
      - name: varnish
        image: varnish:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: varnish-config
          mountPath: /etc/varnish/default.vcl
          subPath: default.vcl
      volumes:
      - name: varnish-config
        configMap:
          name: varnish-config
---
apiVersion: v1
kind: Service
metadata:
  name: varnish
  namespace: public
spec:
  selector:
    app: varnish
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
