/**
 * @fileoverview gRPC-Web generated client stub for gateway
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v3.19.1
// source: report_service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as report_service_pb from './report_service_pb'; // proto import: "report_service.proto"


export class ReportServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetReport = new grpcWeb.MethodDescriptor(
    '/gateway.ReportService/GetReport',
    grpcWeb.MethodType.UNARY,
    report_service_pb.GetReportRequest,
    report_service_pb.GetReportResponse,
    (request: report_service_pb.GetReportRequest) => {
      return request.serializeBinary();
    },
    report_service_pb.GetReportResponse.deserializeBinary
  );

  getReport(
    request: report_service_pb.GetReportRequest,
    metadata?: grpcWeb.Metadata | null): Promise<report_service_pb.GetReportResponse>;

  getReport(
    request: report_service_pb.GetReportRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: report_service_pb.GetReportResponse) => void): grpcWeb.ClientReadableStream<report_service_pb.GetReportResponse>;

  getReport(
    request: report_service_pb.GetReportRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: report_service_pb.GetReportResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/gateway.ReportService/GetReport',
        request,
        metadata || {},
        this.methodDescriptorGetReport,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/gateway.ReportService/GetReport',
    request,
    metadata || {},
    this.methodDescriptorGetReport);
  }

  methodDescriptorListReports = new grpcWeb.MethodDescriptor(
    '/gateway.ReportService/ListReports',
    grpcWeb.MethodType.UNARY,
    report_service_pb.ListReportsRequest,
    report_service_pb.ListReportsResponse,
    (request: report_service_pb.ListReportsRequest) => {
      return request.serializeBinary();
    },
    report_service_pb.ListReportsResponse.deserializeBinary
  );

  listReports(
    request: report_service_pb.ListReportsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<report_service_pb.ListReportsResponse>;

  listReports(
    request: report_service_pb.ListReportsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: report_service_pb.ListReportsResponse) => void): grpcWeb.ClientReadableStream<report_service_pb.ListReportsResponse>;

  listReports(
    request: report_service_pb.ListReportsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: report_service_pb.ListReportsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/gateway.ReportService/ListReports',
        request,
        metadata || {},
        this.methodDescriptorListReports,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/gateway.ReportService/ListReports',
    request,
    metadata || {},
    this.methodDescriptorListReports);
  }

}

