prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'load-balancer-metrics'
        static_configs:
          - targets: ['192.168.5.50:8405', '192.168.5.100:8405']
grafana:
  grafana.ini:
    server:
      root_url: "https://grafana.dev.nuage"
    auth.anonymous:
      enabled: true
    security:
      allow_embedding: true
