- name: Get iso
  ansible.builtin.get_url:
    dest: /root/noble-server-cloudimg-amd64.img
    url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
    mode: "0644"

- name: Create VM
  ansible.builtin.shell: |
    qm create {{ item.vmid }} \
      --net0 virtio,bridge=vmbr0 \
      --scsihw virtio-scsi-pci \
      --sockets 1 \
      --scsi0 local-lvm:0,import-from=/root/noble-server-cloudimg-amd64.img \
      --ide2 local-lvm:cloudinit \
      --boot order=scsi0 \
      --onboot 1 \
      --sshkey ~/.ssh/authorized_keys \
      {{ item.options }}

    qm resize {{ item.vmid }} scsi0 +40G
  register: result
  changed_when: result.rc == 0
  when: inventory_hostname == item.target_host
  loop: "{{ vm }}"
