- name: Setup
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts: all
  become: true
  roles:
    - wait-cloud-init
    - setup-libs
    - prometheus.prometheus.node_exporter # mac の場合、brew install gnu-tar が必要だった
    - setup-promtail
