- name: Install packages
  ansible.builtin.apt:
    name:
      - dnsmasq
    state: present

- name: Dnsmasq.conf
  ansible.builtin.copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    mode: "0644"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
  notify:
    - Restart dnsmasq

- name: Custom dns.conf
  ansible.builtin.copy:
    src: dns.conf
    dest: /etc/dnsmasq.d/dns.conf
    mode: "0644"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
  notify:
    - Restart dnsmasq

# release port 53
- name: Edit /etc/systemd/resolved.conf
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: "DNSStubListener=.*"
    line: "DNSStubListener=no"
  notify:
    - Restart systemd-resolved
