- name: Setup proxy
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts: all
  become: true

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - squid
        state: present
        update_cache: true

    - name: Squid.conf
      ansible.builtin.copy:
        src: squid.conf
        dest: /etc/squid/squid.conf
        mode: "0644"
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"

    - name: Restart squid
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
        enabled: true
      with_items:
        - squid
