- name: Setup proxy
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts: all
  become: true

  tasks:
    - name: Wait cloud-init
      ansible.builtin.command:
        cloud-init status
      register: cloudinit_status
      retries: 5
      delay: 10
      until: "'done' in cloudinit_status.stdout"
      changed_when: false

    - name: Slurp the netplan file
      ansible.builtin.slurp:
        src: /etc/netplan/50-cloud-init.yaml
      register: netplan_file

    - name: Decode and parse the YAML content
      ansible.builtin.set_fact:
        netplan_data: "{{ netplan_file.content | b64decode | from_yaml }}"

    - name: Update Netplan
      ansible.builtin.template:
        src: netplan-cloud-init.yaml.j2
        dest: /etc/netplan/50-cloud-init.yaml
        owner: root
        group: root
        mode: "0600"
        backup: true

    - name: Squid.conf
      ansible.builtin.copy:
        src: squid.conf
        dest: /etc/squid/squid.conf
        mode: "0644"
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"

    - name: Install packages
      ansible.builtin.apt:
        name:
          - squid
        state: present
        update_cache: true

    - name: Restart squid
      ansible.builtin.service:
        name: squid
        state: restarted
        enabled: true
