- name: Setup proxy
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts: all
  become: true

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - squid
        state: present
        update_cache: true

    - name: Squid.conf
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/etc/squid/{{ item }}"
        mode: "0644"
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"
      with_items:
        - squid.conf
        - squid-to-external.conf

    - name: Add service file
      ansible.builtin.copy:
        src: squid-to-external.service
        dest: /etc/systemd/system/squid-to-external.service
        mode: "0644"
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"

    - name: Start daemon
      ansible.builtin.systemd:
        state: started
        daemon_reload: true
        name: "{{ item }}"
        enabled: true
      with_items:
        - squid
        - squid-to-external

    - name: Reconfigure
      ansible.builtin.command:
        squid -k reconfigure -f {{ item }}
      changed_when: true
      with_items:
        - /etc/squid/squid.conf
        - /etc/squid/squid-to-external.conf
