- name: Setup router nodes
  hosts: localhost
  vars_files:
    - vars/common.yml
    - vars/secrets.yml
  roles:
    - prepare-variable
    - router-setup-nodes

- name: Setup router network
  hosts: router
  become: true
  vars_files:
    - vars/common.yml
  roles:
    - prepare-variable
    - router-prepare
    - router-enable-nat
    - router-setup-dns
    - router-setup-dhcp
    - router-setup-proxmox-answer-server

- name: Setup cluster nodes
  hosts: localhost
  vars_files:
    - vars/common.yml
    - vars/secrets.yml
  roles:
    - prepare-variable
    - cluster-setup-nodes
