apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
  namespace: nuage-monitoring
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: gateway
      containers:
      - name: gateway
        image: ghcr.io/k-wa-wa/nuage-monitoring-gateway
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: DB_PASSWORD
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: DB_PORT
          - name: MICRO_GOPUSH_URL
            value: http://push-server.nuage-monitoring.svc.cluster.local
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "2"
            memory: "4096Mi"
          requests:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: nuage-monitoring
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30081
  type: NodePort
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway
  namespace: nuage-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-role
rules:
- apiGroups: ["example.com"] # 操作するリソースのAPIグループ
  resources: ["applicationlists"] # 操作を許可するリソース
  verbs: ["get", "list", "watch"] # 許可する操作
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-binding
subjects:
- kind: ServiceAccount
  name: gateway
  namespace: nuage-monitoring
roleRef:
  kind: ClusterRole
  name: gateway-role
  apiGroup: rbac.authorization.k8s.io
