apiVersion: apps/v1
kind: Deployment
metadata:
  name: vis-chart-server
  labels:
    app: vis-chart-server
  namespace: nuage-monitoring
spec:
  selector:
    matchLabels:
      app: vis-chart-server
  template:
    metadata:
      labels:
        app: vis-chart-server
    spec:
      containers:
      - name: vis-chart-server
        image: ghcr.io/k-wa-wa/nuage-monitoring-vis-chart-server
        env:
          - name: AWS_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: AWS_ENDPOINT
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: AWS_REGION
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: AWS_SECRET_ACCESS_KEY
          - name: S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: S3_BUCKET_NAME
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: vis-chart-server
  namespace: nuage-monitoring
spec:
  selector:
    app: vis-chart-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
