apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: nuage-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: nuage-tls-credential
    hosts:
    - "*"
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: file-server-virtualservice
  namespace: default
spec:
  hosts:
  - "file-server.nuage"
  gateways:
  - nuage-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: file-server-ui-service.pechka.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argo-workflow-virtualservice
  namespace: default
spec:
  hosts:
  - "workflow.dev.nuage"
  gateways:
  - nuage-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: argo-workflow-bff.pechka.svc.cluster.local
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: dashboard-virtualservice
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - nuage-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: nuage-dashboard-service.default.svc.cluster.local
        port:
          number: 80
