apiVersion: v1
kind: Node
metadata:
  name: oc1-pi-2
  labels:
    node-type: pi5.medium
---
apiVersion: v1
kind: Node
metadata:
  name: worker-node-01
  labels:
    node-type: pv1.small
---
apiVersion: v1
kind: Node
metadata:
  name: worker-node-02
  labels:
    node-type: pv1.medium
---
apiVersion: v1
kind: Node
metadata:
  name: worker-node-device-host-01
  labels:
    node-type: pv1.medium
    bluray-disk-device: "true"
