apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: nuage-postgres
spec:
  teamId: "nuage"
  spiloRunAsUser: 101
  spiloRunAsGroup: 103
  spiloFSGroup: 103
  volume:
    size: 16Gi
  numberOfInstances: 2
  postgresql:
    version: "16"
