CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:IyxEFqNA6ova6TS/ONzOHl1bJbUPaXrUHuizJWCeDxBuBdPgBzyV+ikeCaIt+EphG54/7/s=,iv:dXqexQJNdDokAgNvryOHPqLyfVEAR4ZUUCpf70mSSDM=,tag:+cZV3OPuwYhFeFuCOSbDxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17e67u5g3j9v6sxxrk448gsgmv9ldc2umqgad579du75fgjkjtcasatrhxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBc3RaZW1LZldOSlB0aUI2
            aTEyWlpQSEFLNEk2MFhmT053RlBCNUxHWFdjCmtxY0RGSkxrdmlqelM3QzZSb0Rr
            dStRZzgrNEhwczRWQVFiZTBrbEVDR0UKLS0tIDZOejFoRjVVM2w5YWNDVFJ3NmVa
            dW1WcUluM0lHT0tyRWdwa0N2QWMvaHMKAljRkMcNdKe8Hj+LZhgyq9mqJzOMaHj7
            9TkCw0OMX1CfMf6/wCGyF5w3Q5WcwHVMiwICy7+yrlQHNes0dKifuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vqgm0gczrwyluk9lyhpz49uea7m04u53q4c60kwn9s6wuguhju3qjznrut
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNDdnY0dmQW5ZT1lBRnBG
            UnlXQXlLVW50MldYWDRDeGFzQmFCWGs3ZG1JCjVkMDRsZ296bXgvcHFrdlVBdGJ4
            ZzZ2Zm5CM3B1cG43dUNZZlRsQVR3Z00KLS0tIFhMbzRtSTAwMXlub1pOcjl0Y1VB
            MVROMExjSkRmS0p6V3I1eE9Td1RjZ1UKHrSl15SNVE3I3mPl/WqOgYE38Zdog/oi
            341lrw+XT3mHHeLqueyHj6s9PuNejcMA+YyIQkm5WB5+KsRY/IOK1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T13:38:04Z"
    mac: ENC[AES256_GCM,data:57+LN5XwCwNYJf4ysU/ZJOBI0B0B7KFh/K5tJ3M6Ke9YDQalauv/Fcd0DnbkMvhEt45YB97zIRcsSNiIGIzpCaFSYMpaaDtS8CqY0jjieYa1N6FkzKDqKiLkQ5iQjAkpS6u/jqG4y9jXj78L7Irhhx8crHhFr+rwoqAD6YeBfq0=,iv:ACas8scTd7s72SFTpc3xRtE9vVzhSSChxgmijsF4470=,tag:OjTMaP5ypiGMcpqL1YrjVQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
