apiVersion: v1
kind: PersistentVolume
metadata:
  name: nufs-pv
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: nodeName
              operator: In
              values:
                - nuage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nufs-pvc
spec:
  resources:
    requests:
      storage: 1000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
