apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
  namespace: litellm
type: Opaque
stringData:
  SAKURA_API_KEY: "<path:secrets.yaml#SAKURA_API_KEY>"
  GEMINI_API_KEY: "<path:secrets.yaml#GEMINI_API_KEY>"
