SAKURA_API_KEY: ENC[AES256_GCM,data:ktT2DzpGf5W2z4JUCC6v8Wlw98nTP3cW6zDkNKEFCpC34qqB6bEwqnPiw59DhAnPMzNvxpNvyoy/hELQDf6J/tmyihHv5Yupdm9GEzA=,iv:BLn2yXGUzdWVn7EW5WqbyjtBXvsLjUTE6qV3meCTYO4=,tag:o3bh5wmvRAbZNhjoxTdeGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17e67u5g3j9v6sxxrk448gsgmv9ldc2umqgad579du75fgjkjtcasatrhxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeXRJVlYvRG9IejJLUWtW
            ck5Uc3drZ05DWXJ1a1R5dXpRNHhleGdxZW5BCnNIak93MERBUDE1Z082R050YmtK
            dlhSZmoxYlR3WVV5aElRTE9Qbm5sVXcKLS0tIDdRYU9aR25oMzExYlA4VzVWdHlV
            b3A1dGg3dEd6QlhqTWtXWWdvdGFxNVkKQxQSzKENh2rUU/3d5ohwsr/iziPo8uMY
            0mch11qNSLg0YvDSAVC6qAzW+wyv2TjS0lJ8BDNbFK5mvLPZwO4L4g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vqgm0gczrwyluk9lyhpz49uea7m04u53q4c60kwn9s6wuguhju3qjznrut
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHT25yWW83K0dNUmFYZjhF
            Yi9EYVhSYjBlR1R3cjlmZkd2czAxY2Y4RW44CjhnM1RnUEVDbEdtamRRSk5oL1dj
            UW5tZmpuT1pMSGxIOHcvNlhCazZqR00KLS0tIHBSUFZBZzJFN3lPN2swL1VQRVgy
            ZzA4SSt2YUZ4Q1RWUFhkMXMveW5oWTQKRz28YXhJzTT8gO2d64q7nDvm8O6sF6ps
            7JpSUixBf5oOxtwaaVYMdQXN2c/AiAZnasOWngymWZB/J1bvoEfv0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T03:36:50Z"
    mac: ENC[AES256_GCM,data:LE9iJ2/O7L4LOBqUPmEDQEETJX6z3Me+xvepFx9woA9Q2gkIwRuqXuv0RJwTY6v+DPXYzJTDv5vl8jqHGwP0v95PrPzHqwFwwp114m+kMd3Qee7JsE3DTr91UjglKgRuFBXssMl6Vt/CPrQdlneSBa2JZipHJ0sAekIGPZ2N5gc=,iv:eSw4wg6n2n7fd27XlDoDS5pSL25efa0dkxP/oMNEwoM=,tag:0yRBTfWbtXi2RxPHzyv0rw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
