- name: Generate hosts.yml
  ansible.builtin.copy:
    dest: 'hosts.yml'
    mode: "0644"
    content: |
      all: # noqa: syntax-check[specific]
        hosts:
      {% for subnet in subnets_config %}
          {{ subnet.gateway.name }}:
            ansible_host: {{ subnet.gateway.public_ip }}
            ansible_user: ubuntu
            ansible_ssh_private_key_file: ./.ssh/id_rsa
      {% endfor %}

        children:
          gateway-nodes:
            hosts:
      {% for subnet in subnets_config %}
              {{ subnet.gateway.name }}:
      {% endfor %}

- name: Generate hosts-pve-nodes.yml
  ansible.builtin.copy:
    dest: "../pve-cluster/hosts-pve-{{ item.cidr | replace('/', '_') }}.yml"
    mode: "0644"
    content: |
      all: # noqa: syntax-check[specific]
        hosts:
      {% for pve_node in item.pve_nodes %}
          {{ pve_node.name }}:
            ansible_host: {{ pve_node.ip }}
            ansible_user: {{ pve_node.user | replace('@pam', '') }}
            ansible_password: {{ pve_node.password }}
      {% endfor %}
  loop: "{{ subnets_config }}"
