- name: Generate hosts.yml
  ansible.builtin.copy:
    dest: 'hosts.yml'
    mode: "0644"
    content: |
      all: # noqa: syntax-check[specific]
        hosts:
      {% for subnet in subnets_config %}
          {{ subnet.gateway.name }}:
            ansible_host: {{ subnet.gateway.public_ip }}
            ansible_user: ubuntu
            ansible_ssh_private_key_file: ./.ssh/id_rsa
      {% endfor %}

        children:
          gateway-nodes:
            hosts:
      {% for subnet in subnets_config %}
              {{ subnet.gateway.name }}:
      {% endfor %}
