- name: Generate hosts.yml
  ansible.builtin.copy:
    dest: 'hosts.yml'
    mode: "0644"
    content: |
      all: # noqa: syntax-check[specific]
        hosts:
      {% for host in gateway_vms_config %}
          {{ host.name }}:
            ansible_host: {{ host.public_ip }}
            ansible_user: ubuntu
            ansible_ssh_private_key_file: ./.ssh/id_rsa
            gateway_ip: {{ host.ip }}
            cidr: {{ host.cidr }}
      {% endfor %}

        children:
          gateway-nodes:
            hosts:
      {% for host in gateway_vms_config %}
              {{ host.name }}:
      {% endfor %}
