apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  labels:
    app: report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
      - name: report-service
        image: report-service:latest
        imagePullPolicy: Never
        ports:
        - name: grpc
          containerPort: 5051
        - name: http
          containerPort: 5052
        env:
        - name: ES_URL
          value: http://elasticsearch-master:9200
        - name: ES_USERNAME
          value: ""
        - name: ES_PASSWORD
          value: ""
        - name: EMBEDDING_URL
          value: http://ollama:11434/v1
        - name: EMBEDDING_MODEL
          value: nomic-embed-text
---
apiVersion: v1
kind: Service
metadata:
  name: report-service
spec:
  selector:
    app: report-service
  ports:
  - name: grpc
    protocol: TCP
    port: 80
    targetPort: 5051
  - name: http
    protocol: TCP
    port: 5052
    targetPort: 5052
  type: ClusterIP
