- name: Read join info json
  ansible.builtin.set_fact:
    kubeadm_join_info: "{{ lookup('file', './kubeadm_join_info.json') | from_json }}"
  delegate_to: localhost

- name: Join control plane # noqa: no-changed-when
  ansible.builtin.command: |
    {{ kubeadm_join_info.join_command }} \
      --control-plane \
      --apiserver-advertise-address={{ ansible_host }} \
      --certificate-key {{ kubeadm_join_info.certificate_key }}
