- name: Install packages
  ansible.builtin.apt:
    name:
      - openssl
      - haproxy
      - keepalived
    state: present
    update_cache: true

- name: Extract node IPs
  ansible.builtin.set_fact:
    node_ips: "{{ groups['node'] | map('extract', hostvars, 'ansible_host') | list }}"

- name: Create HAProxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "0640"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    backup: true

- name: Copy keepalived.conf (Master)
  ansible.builtin.copy:
    src: keepalived_master.conf
    dest: /etc/keepalived/keepalived.conf
    mode: "0640"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    backup: true
  when: inventory_hostname == groups["service-lb"][0]

- name: Copy keepalived.conf (Backup)
  ansible.builtin.copy:
    src: keepalived_backup.conf
    dest: /etc/keepalived/keepalived.conf
    mode: "0640"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    backup: true
  when: inventory_hostname != groups["service-lb"][0]

- name: Start haproxy & keepalived
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - haproxy
    - keepalived
