apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pechka

resources:
  - ../../base
  - minio/
  - secrets/api-secret.yaml
  - secrets/benthos-secret.yaml
  - secrets/mongodb-secret.yaml
  - secrets/minio-secret.yaml
  - secrets/pechka-postgres.yaml

images:
  - name: ghcr.io/k-wa-wa/pechka-api
    newTag: "8bcd82c"
  - name: ghcr.io/k-wa-wa/pechka-frontend
    newTag: "8bcd82c"
