apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server-api-deployment
  labels:
    app: file-server-api
spec:
  selector:
    matchLabels:
      app: file-server-api
  template:
    metadata:
      labels:
        app: file-server-api
    spec:
      containers:
        - name: file-server-api
          image: ghcr.io/k-wa-wa/pechka-file-server-api
          ports:
            - containerPort: 8000
          # resources:
          #   limits:
          #     memory: 4Gi
          #     cpu: "1"
          volumeMounts:
            - name: mnt-bluray
              mountPath: "/mnt/hls" # TODO: hlsディレクトリだけ読めるようにした方がいい
          env:
            - name: HLS_RESOURCE_DIR
              value: /mnt/hls
            - name: DB_HOST
              value: nuage-postgres.postgres.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres.nuage-postgres.credentials.postgresql.acid.zalan.do
                  key: username
                  optional: false
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.nuage-postgres.credentials.postgresql.acid.zalan.do
                  key: password
                  optional: false
            - name: DB_NAME
              value: pechka
      volumes:
        - name: mnt-bluray
          persistentVolumeClaim:
            claimName: nfs-bluray-hls-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: file-server-api-service
spec:
  selector:
    app: file-server-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
