apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-bluray-hls-pv
spec:
  capacity:
    storage: 1Gi # 必須のため最小容量を設定
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /srv/nfs/bluray/hls
    server: 192.168.5.151
  mountOptions:
    - vers=4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-bluray-hls-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi # 必須のため最小容量を設定
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server-api-deployment
  labels:
    app: file-server-api
spec:
  selector:
    matchLabels:
      app: file-server-api
  template:
    metadata:
      labels:
        app: file-server-api
    spec:
      containers:
        - name: file-server-api
          image: ghcr.io/k-wa-wa/pechka-file-server-api
          ports:
            - containerPort: 8000
          # resources:
          #   limits:
          #     memory: 4Gi
          #     cpu: "1"
          volumeMounts:
            - name: mnt-bluray
              mountPath: "/mnt/hls" # TODO: hlsディレクトリだけ読めるようにした方がいい
          env:
            - name: HLS_RESOURCE_DIR
              value: /mnt/hls
      volumes:
        - name: mnt-bluray
          persistentVolumeClaim:
            claimName: nfs-bluray-hls-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: file-server-api-service
spec:
  selector:
    app: file-server-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
