apiVersion: batch/v1
kind: CronJob
metadata:
  name: file-server-data-importer-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: file-server-data-importer
              image: ghcr.io/k-wa-wa/pechka-file-server-data-importer
              volumeMounts:
                - name: mnt-hls
                  mountPath: "/mnt/hls"
              env:
                - name: HLS_RESOURCE_DIR
                  value: /mnt/hls
                - name: DB_HOST
                  value: postgres.default.svc.cluster.local
                - name: DB_PORT
                  value: "5432"
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: user
                      optional: false
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: password
                      optional: false
                - name: DB_NAME
                  value: pechka
          restartPolicy: Never
          volumes:
            - name: mnt-hls
              persistentVolumeClaim:
                claimName: nfs-hls-pvc
