apiVersion: batch/v1
kind: CronJob
metadata:
  name: file-server-refresh-latest-playlist-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: file-server-refresh-latest-playlist
              image: ghcr.io/k-wa-wa/pechka-file-server-refresh-latest-playlist
              env:
                - name: DB_HOST
                  value: postgres.default.svc.cluster.local
                - name: DB_PORT
                  value: "5432"
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: user
                      optional: false
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: password
                      optional: false
                - name: DB_NAME
                  value: pechka
          restartPolicy: Never
