apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server-ui-deployment
  labels:
    app: file-server-ui
spec:
  selector:
    matchLabels:
      app: file-server-ui
  template:
    metadata:
      labels:
        app: file-server-ui
    spec:
      containers:
        - name: file-server-ui
          image: ghcr.io/k-wa-wa/pechka-file-server-ui
          ports:
            - containerPort: 3000
          command: [
            "/bin/bash", "-c",
            "API_URL=http://file-server-api-service.default.svc.cluster.local:8000 ./node_modules/.bin/remix-serve ./build/server/index.js"
          ]
          # resources:
          #   limits:
          #     memory: 4Gi
          #     cpu: "500m"
          env:
            - name: API_URL
              value: http://file-server-api-service.default.svc.cluster.local:8000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: file-server-ui-service
spec:
  selector:
    app: file-server-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30101
  type: NodePort

