apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-hls-pv
spec:
  capacity:
    storage: 1Gi # 必須のため最小容量を設定
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /srv/nfs/hls
    server: 192.168.5.151
  mountOptions:
    - vers=4
  storageClassName: nfs-hls-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-hls-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi # 必須のため最小容量を設定
  volumeName: nfs-hls-pv
  storageClassName: nfs-hls-sc
