- name: Create a Proxmox VE Cluster
  community.proxmox.proxmox_cluster:
    state: present
    api_host: "{{ proxmox_vms[0].ip }}"
    api_user: "{{ proxmox_vms[0].user }}"
    api_password: "{{ proxmox_vms[0].password }}"
    validate_certs: false
    cluster_name: "dev-cluster"
  run_once: true

- name: List existing Proxmox VE cluster join information
  community.proxmox.proxmox_cluster_join_info:
    api_host: "{{ proxmox_vms[0].ip }}"
    api_user: "{{ proxmox_vms[0].user }}"
    api_password: "{{ proxmox_vms[0].password }}"
  register: proxmox_cluster_join
  until: proxmox_cluster_join is success
  retries: 5
  delay: 10
  run_once: true

- name: Join nodes
  ansible.builtin.include_tasks: join-node.yml
  loop: "{{ proxmox_vms[1:] }}"
