# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\nai_service\"O\n\x15GenerateReportRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x0cinstructions\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\t\"^\n\x16GenerateReportResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\"\n\x06report\x18\x03 \x01(\x0b\x32\x12.ai_service.Report\"%\n\x06Report\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t2d\n\tAIService\x12W\n\x0eGenerateReport\x12!.ai_service.GenerateReportRequest\x1a\".ai_service.GenerateReportResponseB<Z:github.com/nuage-cluster/monitoring-stack/ai-service/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/nuage-cluster/monitoring-stack/ai-service/proto'
  _globals['_GENERATEREPORTREQUEST']._serialized_start=32
  _globals['_GENERATEREPORTREQUEST']._serialized_end=111
  _globals['_GENERATEREPORTRESPONSE']._serialized_start=113
  _globals['_GENERATEREPORTRESPONSE']._serialized_end=207
  _globals['_REPORT']._serialized_start=209
  _globals['_REPORT']._serialized_end=246
  _globals['_AISERVICE']._serialized_start=248
  _globals['_AISERVICE']._serialized_end=348
# @@protoc_insertion_point(module_scope)
