- name: Setup VM
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts: all
  become: true
  vars:
    vm:
      - target_host: oc1-server1
        vmid: 5152
        options: "--memory 98304 --cores 15 --name oc1-lm-server --ipconfig0 ip=192.168.5.152/24,gw=192.168.5.1 -machine q35"
        healthcheck_ip: 192.168.5.152
        shell_command: "qm resize 5152 scsi0 +256G && qm set 5152 --hostpci0 0000:2d:00,pcie=1"
  roles:
    - destroy-vm
    - create-vm
    - start-vm
