all:
  vars:
    ansible_ssh_private_key_file: ./.ssh/id_rsa
  children:
    dns_servers:
      hosts:
        oc1-dns:
          ansible_host: 192.168.5.161
          ansible_user: ubuntu
    proxy_servers:
      hosts:
        oc1-proxy:
          ansible_host: 192.168.5.160
          ansible_user: ubuntu
