apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero
spec:
  schedule: 15 12 * * *
  template:
    ttl: 72h0m0s
    includedNamespaces:
    - default
    includedResources:
    - pv
    - pvc
    snapshotVolumes: true
