- name: Install deps
  ansible.builtin.apt:
    name:
      - kea-dhcp4-server
    state: present
    update_cache: true

- name: Get subnet
  ansible.builtin.set_fact:
    subnet: "{{ subnets_config | selectattr('gateway.name', 'equalto', inventory_hostname) | list | first }}"

- name: Configure kea-dhcp4-server
  ansible.builtin.template:
    src: kea-dhcp4.conf.j2
    dest: /etc/kea/kea-dhcp4.conf
    owner: root
    group: root
    mode: '0644'
  vars:
    pve_nodes: "{{ subnet.pve_nodes }}"
    gateway_ip: "{{ subnet.gateway.ip }}"
    cidr: "{{ subnet.cidr }}"
  notify: Restart kea-dhcp4-server
