apiVersion: v1
kind: Service
metadata:
  name: primary
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: primary-slice
  labels:
    kubernetes.io/service-name: primary
addressType: IPv4
ports:
- port: 5432
endpoints:
- addresses:
  - 10.20.1.28
  conditions: {}
