apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-youtube-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi # 必須のため最小容量を設定
  volumeName: nfs-youtube-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-hls-pv-for-youtube
spec:
  capacity:
    storage: 1Gi # 必須のため最小容量を設定
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/hls
    server: 192.168.5.151
  mountOptions:
    - vers=4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-hls-pvc-for-youtube
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi # 必須のため最小容量を設定
  volumeName: nfs-hls-pv-for-youtube
