// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: report_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`                   // レポートを一意に識別するID
	ReportBody    string                 `protobuf:"bytes,2,opt,name=report_body,json=reportBody,proto3" json:"report_body,omitempty"`             // レポート本文 (ベクトル化の対象)
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // 作成者/通知先ユーザーID
	CreatedAtUnix int64                  `protobuf:"varint,4,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"` // 作成日時 (Unixタイムスタンプ)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReportRequest) Reset() {
	*x = CreateReportRequest{}
	mi := &file_report_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportRequest) ProtoMessage() {}

func (x *CreateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportRequest.ProtoReflect.Descriptor instead.
func (*CreateReportRequest) Descriptor() ([]byte, []int) {
	return file_report_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *CreateReportRequest) GetReportBody() string {
	if x != nil {
		return x.ReportBody
	}
	return ""
}

func (x *CreateReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateReportRequest) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type CreateReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReportResponse) Reset() {
	*x = CreateReportResponse{}
	mi := &file_report_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportResponse) ProtoMessage() {}

func (x *CreateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportResponse.ProtoReflect.Descriptor instead.
func (*CreateReportResponse) Descriptor() ([]byte, []int) {
	return file_report_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_report_service_proto protoreflect.FileDescriptor

const file_report_service_proto_rawDesc = "" +
	"\n" +
	"\x14report_service.proto\x12\x0ereport_service\"\x94\x01\n" +
	"\x13CreateReportRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x1f\n" +
	"\vreport_body\x18\x02 \x01(\tR\n" +
	"reportBody\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12&\n" +
	"\x0fcreated_at_unix\x18\x04 \x01(\x03R\rcreatedAtUnix\"J\n" +
	"\x14CreateReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2j\n" +
	"\rReportService\x12Y\n" +
	"\fCreateReport\x12#.report_service.CreateReportRequest\x1a$.report_service.CreateReportResponseB\x1cZ\x1areport-service/internal/pbb\x06proto3"

var (
	file_report_service_proto_rawDescOnce sync.Once
	file_report_service_proto_rawDescData []byte
)

func file_report_service_proto_rawDescGZIP() []byte {
	file_report_service_proto_rawDescOnce.Do(func() {
		file_report_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_service_proto_rawDesc), len(file_report_service_proto_rawDesc)))
	})
	return file_report_service_proto_rawDescData
}

var file_report_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_report_service_proto_goTypes = []any{
	(*CreateReportRequest)(nil),  // 0: report_service.CreateReportRequest
	(*CreateReportResponse)(nil), // 1: report_service.CreateReportResponse
}
var file_report_service_proto_depIdxs = []int32{
	0, // 0: report_service.ReportService.CreateReport:input_type -> report_service.CreateReportRequest
	1, // 1: report_service.ReportService.CreateReport:output_type -> report_service.CreateReportResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_report_service_proto_init() }
func file_report_service_proto_init() {
	if File_report_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_service_proto_rawDesc), len(file_report_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_report_service_proto_goTypes,
		DependencyIndexes: file_report_service_proto_depIdxs,
		MessageInfos:      file_report_service_proto_msgTypes,
	}.Build()
	File_report_service_proto = out.File
	file_report_service_proto_goTypes = nil
	file_report_service_proto_depIdxs = nil
}
