- name: Reset kubeadm
  ansible.builtin.command: |
    kubeadm reset --force
  register: result
  changed_when: result.rc == 0
  failed_when: false

- name: Stop kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: stopped
  failed_when: false

- name: Remove directory if it exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/kubernetes/
    - ~/.kube/
    - /var/lib/kubelet/
    - /var/lib/cni/
    - /etc/cni/
    - /var/lib/etcd/

- name: Reset iptables
  ansible.builtin.shell: |
    iptables -F && iptables -X
  register: result
  changed_when: result.rc == 0

- name: Reboot（network interfaceをリセットしてkube-vipの残骸を消したい）
  ansible.builtin.reboot:
    reboot_timeout: 300
    connect_timeout: 300
