apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: postgres-credentials
  namespace: default
  envs:
  - .env.postgres-credentials
- name: postgres-credentials
  namespace: nuage-monitoring
  envs:
  - .env.postgres-credentials
- name: s3-credentials
  namespace: nuage-monitoring
  envs:
  - .env.s3-credentials
