apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litellm

resources:
- namespace.yaml
- service.yaml
- deployment.yaml
- gemini-live-proxy-config.yaml
- gemini-live-proxy-deployment.yaml
- gemini-live-proxy-service.yaml
- open-webui-deployment.yaml
- open-webui-service.yaml

configMapGenerator:
- name: litellm-config
  files:
  - config.yaml
