- name: Generate hosts.yml
  ansible.builtin.copy:
    dest: 'hosts.yml'
    mode: "0644"
    content: |
      all: # noqa: syntax-check[specific]
        hosts:
          router:
            ansible_host: {{ router_vm.ip }}
            ansible_user: ubuntu
            ansible_ssh_private_key_file: ./.ssh/id_rsa

      {% for host in proxmox_vms %}
          {{ host.name }}:
            ansible_host: {{ host.ip }}
            ansible_user: {{ host.user | replace("@pam", "") }}
            ansible_password: {{ host.password }}
      {% endfor %}

        children:
          pve-nodes:
            hosts:
      {% for host in proxmox_vms %}
              {{ host.name }}:
      {% endfor %}
