apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pechka

resources:
  - namespace.yaml
  - api.yaml
  - frontend.yaml
  - nginx.yaml
  - benthos.yaml
  - mongodb.yaml
  - elasticsearch.yaml
  - ingress.yaml
