- name: Destroy VM
  ansible.builtin.shell: |
    qm stop {{ item.vmid }}
    qm destroy {{ item.vmid }}
  register: result
  changed_when: result.rc == 0
  when: inventory_hostname == item.target_host
  loop: "{{ vm }}"
  ignore_errors: true
