# api-prototype
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-prototype
spec:
  selector:
    matchLabels:
      app: api-prototype
  template:
    metadata:
      labels:
        app: api-prototype
    spec:
      containers:
      - name: api-prototype
        image: ghcr.io/k-wa-wa/pechka-api-prototype:ec2c0b5
        resources:
          limits:
            memory: 256Mi
            cpu: 1
        ports:
        - containerPort: 8000
        env:
          - name: GOOGLE_API_KEY
            valueFrom:
              secretKeyRef:
                name: pechka-api-secret
                key: GOOGLE_API_KEY
  replicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: api-prototype
spec:
  selector:
    app: api-prototype
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
