apiVersion: v1
kind: Pod
metadata:
  name: door-guard
spec:
  containers:
    - name: door-guard
      image: ghcr.io/k-wa-wa/pechka-door-guard
      volumeMounts:
        - mountPath: "/var/run/dbus"
          name: dbus
      securityContext:
        privileged: true
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
      env:
        - name: SENSOR_MAC
          value: xxx
        - name: IPHONE_HOSTNAME
          value: xxx
        - name: SLACK_WEBHOOK_URL
          value: xxx
  nodeName: nuage
  hostNetwork: true
  volumes:
  - name: dbus
    hostPath:
      path: "/var/run/dbus"
