# ui
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pechka-ui
spec:
  selector:
    matchLabels:
      app: pechka-ui
  template:
    metadata:
      labels:
        app: pechka-ui
    spec:
      containers:
      - name: pechka-ui
        image: ghcr.io/k-wa-wa/pechka-ui:c308d29
        resources:
          limits:
            memory: 256Mi
            cpu: 1
        ports:
        - containerPort: 80
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: pechka-ui
spec:
  selector:
    app: pechka-ui
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
