all: # noqa: syntax-check[specific]
  vars:
    ansible_ssh_private_key_file: ./.ssh/id_rsa
  hosts:
    oc1-pi-1:
      ansible_host: 192.168.5.11
      ansible_user: $OC1_PI_1_USER
    oc1-pi-2:
      ansible_host: 192.168.5.12
      ansible_user: $OC1_PI_2_USER
    oc1-pi-3:
      ansible_host: 192.168.5.13
      ansible_user: $OC1_PI_3_USER
    oc1-pi-4:
      ansible_host: 192.168.5.14
      ansible_user: $OC1_PI_4_USER
    oc1-nuc-1:
      ansible_host: 192.168.5.21
      ansible_user: $OC1_NUC_1_USER
    oc1-nuc-2:
      ansible_host: 192.168.5.22
      ansible_user: $OC1_NUC_2_USER
  children:
    control-plane:
      hosts:
        oc1-pi-1:
    node:
      hosts:
        oc1-pi-2:
        oc1-pi-3:
        oc1-pi-4:
        oc1-nuc-1:
        oc1-nuc-2:
