- name: Setup cluster
  any_errors_fatal: true
  max_fail_percentage: 0
  hosts:
    - control-plane
    - node
  become: true
  roles:
    - 99-reset-kubeadm
    - 01-setup-kubeadm
    - 02-setup-cluster
