- name: Setup gateway VM
  hosts: localhost
  vars_files:
    - vars/secrets.yml
    - vars/common.yml
    - vars/input.yml
  roles:
    - prepare-variable
    - setup-gateway-vm

- name: Setup gateway
  hosts: gateway-nodes
  become: true
  vars_files:
    - vars/common.yml
    - vars/input.yml
  roles:
    - prepare-variable
    - setup-gateway

- name: Setup Proxmox VMs
  hosts: localhost
  vars_files:
    - vars/secrets.yml
    - vars/common.yml
    - vars/input.yml
  roles:
    - prepare-variable
    - setup-pve-vm
