apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-config
data:
  Corefile: |
    .:53 {
        errors
        health
        ready

        hosts {
            192.168.1.10 web.example.com
            192.168.1.11 api.example.com
            fallthrough
        }

        forward . 8.8.8.8 8.8.4.4
        cache 30
        reload
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avenue53
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avenue53
  template:
    metadata:
      labels:
        app: avenue53
    spec:
      containers:
      - name: coredns
        image: coredns/coredns:latest
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
          readOnly: true
        ports:
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
      volumes:
        - name: config-volume
          configMap:
            name: coredns-config
            items:
            - key: Corefile
              path: Corefile
---
apiVersion: v1
kind: Service
metadata:
  name: dns-external
spec:
  selector:
    app: avenue53
  type: LoadBalancer
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
