- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
    enabled: true

- name: Restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
    enabled: true
