apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-bluray-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi # 必須のため最小容量を設定
  volumeName: nfs-bluray-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-hls-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi # 必須のため最小容量を設定
  volumeName: nfs-hls-pv
