- name: Reset kubeadm
  ansible.builtin.include_tasks:
    file: reset-kubeadm.yml

- name: Disable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - haproxy
    - keepalived
    - kubelet
    - containerd
  failed_when: false

- name: Reboot
  ansible.builtin.reboot:
    reboot_timeout: 300
    connect_timeout: 300
